pipeline {
    agent any

    stages {
        stage('Checkout source code') {
          steps {
            git branch: 'main',
            url: 'https://github.com/kienngo/test2pipeline_jenkin.git'
            sh 'ls -la'
          }
        }

        stage('Build') { 
            steps {
				bat 'echo "Hello world"'
            }
        }
    }
}