pipeline {
    agent any

    environment {
        dotnet = 'C:\\Program Files\\dotnet\\dotnet.exe'
    }

    stages {
        stage('Build') { 
            steps {
                bat 'dotnet build ProjectSample.sln --configuration Release'
            }
        }
    }
}
